### ISSUE TITLE
Halo 5 pc support

### ISSUE THREAD

**Issue by Kanken6174** [CYRiXplaysHalo/SpartanFinder#2]
Halo 5 actually exist on pc. It is completely free on the microsoft store and is named halo 5 : forge. I was wondering since you've setup the player count for halo 5 if you would be able to do the same for the pc version?

As there is a very small playerbase (never more than 20+ people online, often 0-6 including myself), knowing WHEN people have started lobbies would be a godsend...

Do you think that might be possible? If you document how you did it for H5 on your github i'm willing to code it myself if needs be...

**Comment by CYRiXplaysHalo** [comment]
Uh I think it could be possible. For Halo 5 I'm using the public API and the most popular twitch streamers to get population numbers. At a high level basically I look to see if any Halo 5 players are online via them livestream on twitch. Then I use the public API to get their most recent games, then I crawl through each player and recurse, until I get every player who played within a 15 minute segment. 

https://developer.haloapi.com/docs/services/

I guess the issue there would be unfortunately the population on Halo 5 PC is very low, and people don't stream. Is there a core group of people that are consistently on? I could probably just constantly ping their most recent games, see if their most recent games were in the last 15 minutes or so, and if they were crawl through the list of active players that way.

**Comment by Kanken6174** [comment]
hmm... when i say the playerbase is very low, it's to the point where there aren't any open lobbies to play on.
![image](https://user-images.githubusercontent.com/49340711/101130954-bb97f800-3604-11eb-9164-509b193142d1.png)
Like, having even one lobby with 2 people on it is rare, but then it often snowballs to 16 players quickly.

If i had to get you the core group of people on this game that would be me i guess X') (morph#8798). I'm hosting something like 90% of the games.

The problem of this game is that whenever people get on the game they often leave after having their lobby empty for 2 minutes, knowing when a lobby opens would solve that issue...

thx for directing me to the api anyways, i did not even know it was a thing!

**Comment by CYRiXplaysHalo** [comment]
I'm assuming you have to use your xbox live gamertag to play this, right? I got a similar request from a player who plays Halo 3 on Xbox 360. The issue I ran into with him is my xbox live gamertag presence crawler takes a few hours to run, so while I could reveal the gamertags of players who were seen playing Halo 3 on Xbox 360, and thus help people find customs, it'd likely be 0.5-2 hours old and people aren't likely to be still on for that long if they aren't finding games. But yeah maybe there's something I can figure out.

One thing that could maybe work is if there is a relative tight community of players that all know each other: start a gamertag for the community and have everyone become friends with it. There is an xbox live xsapi request that is a single request to retrieve a gamertag's friend list, so it would be just one request to see everyone's status. I'd have to double check but it would at least show who's online, but hopefully it would also show what game they are playing.

**Comment by Kanken6174** [comment]
From the reaserch i've done on my part and because of how volatile the H5 pc playerbase is, i don't really think any kind of crawler or community account would work (people come and leave quickly). So i think a lobby finder for H5 isn't really feasable from code, on the other hand, i've hand some luck with an AHK bot running all the time in the background in a VM, it looks for the pixel color of the custom game lobby in the menu and refreshes the page every 30 seconds. If i tinker a bit more with it i think it'll work out.

Only cons: high cpu/gpu usage (h5 menu duh) and overall messy, but it might just work.

Thx for the tips btw, i learnt quite a bit about the xbox live api and other related stuff :)
