### ISSUE TITLE
Add Source Code

### ISSUE THREAD

**Issue by lflo5727** [CYRiXplaysHalo/SpartanFinder#4]
Could this project be open sourced? Looks like the only item in the repo is a readme.
Looks like the site hasn't updated in around 90 days. If its being retired, it'd be nice to have access to the source code so others could spin this up.

**Comment by nmjohnson** [comment]
Yeah if I find some time I'll open source it

**Comment by CYRiXplaysHalo** [comment]
@lflo5727 I am starting to upload the source code now

**Comment by CYRiXplaysHalo** [comment]
@lflo5727 okay all source code should be in repo now. certainly let me know if you have any questions. closing.

**Comment by lflo5727** [comment]
@CYRiXplaysHalo  Awesome, thanks for posting that!
